/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.scep.views;

import br.com.scep.dao.ProdutoDao;
import br.com.scep.model.Estoque;

import br.com.scep.model.Produto;
import br.com.scep.services.EstoqueService;
import br.com.scep.services.ProdutoService;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeffe_cjks0ez
 */
public class EstoqueView extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarProduto
     */
    public EstoqueView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonGerarRelatorio = new javax.swing.JButton();
        jTextFieldPreceProd = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jTextFieldNomeProd = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        jTextFieldQuantProd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();
        jButtonCadastrarProduto = new javax.swing.JButton();
        jButtonAtualizarProduto1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(59, 59, 59));

        jPanel2.setBackground(new java.awt.Color(51, 0, 204));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/label_voltarnov-removebg-preview.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 0, 204));

        jButtonGerarRelatorio.setBackground(new java.awt.Color(51, 0, 204));
        jButtonGerarRelatorio.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButtonGerarRelatorio.setText("Gerar Relatório");
        jButtonGerarRelatorio.setActionCommand("ApagarProduto");
        jButtonGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButtonGerarRelatorio)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTextFieldPreceProd.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPreceProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPreceProdActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Preço do produto");

        label2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Nome do Produto");

        jTextFieldNomeProd.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNomeProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeProdActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Quantidade");

        jTextFieldQuantProd.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldQuantProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantProdActionPerformed(evt);
            }
        });

        jTableProduto.setBackground(new java.awt.Color(255, 255, 255));
        jTableProduto.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTableProduto.setForeground(new java.awt.Color(0, 0, 0));
        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "QUANT", "PREÇO"
            }
        ));
        jTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduto);

        jButtonCadastrarProduto.setBackground(new java.awt.Color(51, 0, 204));
        jButtonCadastrarProduto.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButtonCadastrarProduto.setText("Cadastrar Produto");
        jButtonCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarProdutoActionPerformed(evt);
            }
        });

        jButtonAtualizarProduto1.setBackground(new java.awt.Color(51, 0, 204));
        jButtonAtualizarProduto1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButtonAtualizarProduto1.setText("Atualizar Produto");
        jButtonAtualizarProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarProduto1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/label_estoque-removebg-preview.png"))); // NOI18N

        jButtonApagar.setBackground(new java.awt.Color(51, 0, 204));
        jButtonApagar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButtonApagar.setText("Apagar Produto");
        jButtonApagar.setActionCommand("ApagarProduto");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(jTextFieldNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldQuantProd, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonAtualizarProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPreceProd, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(143, Short.MAX_VALUE))))))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonApagar, jButtonAtualizarProduto1, jButtonCadastrarProduto, jTextFieldNomeProd, jTextFieldPreceProd, jTextFieldQuantProd, label2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQuantProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPreceProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarProduto)
                    .addComponent(jButtonAtualizarProduto1)
                    .addComponent(jButtonApagar))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonApagar, jButtonAtualizarProduto1, jButtonCadastrarProduto, jTextFieldNomeProd, jTextFieldPreceProd, jTextFieldQuantProd, label1, label2, label3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPreceProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPreceProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPreceProdActionPerformed

    private void jButtonGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarRelatorioActionPerformed
        EstoqueService estoqueService = new EstoqueService();
        List<Estoque> estoqueItems = estoqueService.gerarRelatorioEstoque();

        DefaultTableModel model = (DefaultTableModel) jTableProduto.getModel();
        model.setRowCount(0);

        for (Estoque item : estoqueItems) {
            model.addRow(new Object[]{
                item.getId(),
                item.getNomeProduto(),
                item.getQuantidade(),
                item.getValorProduto(),});
        }

    }//GEN-LAST:event_jButtonGerarRelatorioActionPerformed

    private void jTableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutoMouseClicked
        if (jTableProduto.getSelectedRow() != -1) {
            jTextFieldNomeProd.setText(jTableProduto.getValueAt(jTableProduto.getSelectedRow(), 1).toString());
            jTextFieldQuantProd.setText(jTableProduto.getValueAt(jTableProduto.getSelectedRow(), 2).toString());
            jTextFieldPreceProd.setText(jTableProduto.getValueAt(jTableProduto.getSelectedRow(), 3).toString());

        }
    }//GEN-LAST:event_jTableProdutoMouseClicked

    private void jButtonCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarProdutoActionPerformed

        DefaultTableModel listaDeCadastrados = (DefaultTableModel) jTableProduto.getModel();

        ProdutoService produtoService = new ProdutoService();
        EstoqueService estoqueService = new EstoqueService();
        ProdutoDao prodDao = new ProdutoDao();

        if (!produtoService.camposNaoVazios(jTextFieldNomeProd, jTextFieldQuantProd, jTextFieldPreceProd)) {
            JOptionPane.showMessageDialog(null, "Para adicionar, você precisa preencher todos os dados");
            return;
        }

        try {
            String nomeProd = jTextFieldNomeProd.getText().toUpperCase();
            int quantProd = Integer.parseInt(jTextFieldQuantProd.getText());
            double precoProd = Double.parseDouble(jTextFieldPreceProd.getText());
            Produto prod = new Produto();
            prod.setNomeProd(nomeProd);
            prod.setValor_Produto(precoProd);

            try {
                Produto produtoCadastrado = prodDao.cadastrarProduto(prod, quantProd);
                if (produtoCadastrado != null) {
                    JOptionPane.showMessageDialog(null, "CADASTRADO: " + nomeProd.toUpperCase());
                } else {
                    JOptionPane.showMessageDialog(null, "Não foi possível cadastrar: " + nomeProd.toUpperCase());
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "NÃO FOI POSSÍVEL CADASTRAR: " + nomeProd.toUpperCase());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Os valores digitados não são válidos.");
        }


    }//GEN-LAST:event_jButtonCadastrarProdutoActionPerformed

    private void jButtonAtualizarProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarProduto1ActionPerformed

        String nomeProd = jTextFieldNomeProd.getText().toUpperCase();
        int quantProd = Integer.parseInt(jTextFieldQuantProd.getText());
        double precoProd = Double.parseDouble(jTextFieldPreceProd.getText());

        int selectedRow = jTableProduto.getSelectedRow();

        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) jTableProduto.getModel();

            if (model.getColumnCount() >= 4) {
                Object idValue = model.getValueAt(selectedRow, 0);
                int idProduto;
                try {
                    if (idValue instanceof Integer) {
                        idProduto = (Integer) idValue;
                    } else if (idValue instanceof Long) {
                        idProduto = ((Long) idValue).intValue();
                    } else if (idValue instanceof String) {
                        idProduto = Integer.parseInt((String) idValue);
                    } else {
                        throw new ClassCastException("Unexpected ID type");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Erro ao converter ID: " + e.getMessage());
                    return;
                }

                String nomeAntigo = (String) model.getValueAt(selectedRow, 1);
                int quantAntiga = (Integer) model.getValueAt(selectedRow, 2);
                double precoAntigo = (Double) model.getValueAt(selectedRow, 3);

                ProdutoService produtoService = new ProdutoService();
                ProdutoDao prodDao = new ProdutoDao();
                Produto prod = produtoService.criarProdutoModel(nomeProd, precoProd, idProduto);

                if (!nomeProd.equals(nomeAntigo) || precoProd != precoAntigo) {
                    prodDao.atualizarProd(prod);

                    model.setValueAt(nomeProd, selectedRow, 1);
                    model.setValueAt(precoProd, selectedRow, 3);
                    JOptionPane.showMessageDialog(null, "PRODUTO ATUALIZADO: " + nomeProd);
                }

                if (quantProd != quantAntiga) {
                    try {
                        prodDao.atualizarQuantEstoque(idProduto, quantProd);
                    } catch (SQLException ex) {
                        System.err.println("Erro:");
                        ex.printStackTrace();
                    }

                    model.setValueAt(quantProd, selectedRow, 2);
                    JOptionPane.showMessageDialog(null, "QUANTIDADE ATUALIZADA: " + nomeProd);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Erro: Número de colunas insuficiente na tabela.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um produto da tabela para atualizar.");
        }


    }//GEN-LAST:event_jButtonAtualizarProduto1ActionPerformed

    private void jTextFieldQuantProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantProdActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new Menu().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        int selectedRow = jTableProduto.getSelectedRow();
        ProdutoDao dao = new ProdutoDao();

        int idProduto = (int) jTableProduto.getValueAt(selectedRow, 0);

        if (selectedRow != -1) {
            try {
                dao.deletarProduto((int) idProduto);
                JOptionPane.showMessageDialog(null, "PRODUTO APAGADO [ " + idProduto + "]");
            } catch (SQLException ex) {
                Logger.getLogger(EstoqueView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jTextFieldNomeProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstoqueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstoqueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstoqueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstoqueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstoqueView().setVisible(true);
            }
        });
    }

    public JTable getjTableProduto() {
        return jTableProduto;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonAtualizarProduto1;
    private javax.swing.JButton jButtonCadastrarProduto;
    private javax.swing.JButton jButtonGerarRelatorio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JTextField jTextFieldNomeProd;
    private javax.swing.JTextField jTextFieldPreceProd;
    private javax.swing.JTextField jTextFieldQuantProd;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
